apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xendit-ta.name" . }}-api-config
  labels:
    app.kubernetes.io/name: {{ template "xendit-ta.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
type: Opaque
data:
  .xendit-ta.yaml: {{ .Values.config | toYaml | b64enc }}